@startuml

title Post Booking

participant "Client:C" as C
participant "<<Typescript>>:Server" as S
participant "<<router>>:Booking" as R
participant "<<middleware>>:Auth" as A
participant "<<controller>>:Booking" as B
participant "<<model>>:Booking" as M
database "<<MongoDB>>:bookings" as DB

C -> S++: req.post('/bookings')
S -> R++: app.use('/bookings', bookingRouter)
R -> A++: protect()
A -> B++: addBooking()

B -> M++: create(req.body)
M -> DB++: BookingSchema
DB --> M--: booking
M --> B--: booking
B --> C--: response

@enduml